package co.edu.uniquindio.compiladores.lexico
/*
 * @author: Jaime Nieto, Yiran Hernandez, Mauricio Duque
 */
enum class Categoria {

    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_RELACIONAL, OPERADOR_LOGICO, OPERADOR_ASIGNACION,
    PARENTESIS_IZQ, PARENTESIS_DER, LLAVE_IZQ, LLAVE_DER,CORCHETE_IZQ,CORCHETE_DER, TERMINAL, SEPARADOR,
    CADENA_CARACTERES, COMENTARIOLINEA, COMENTARIO_BLOQUE, DESCONOCIDO , PALABRA_RESERVADA,INCREMENTO,DECREMENTO,PUNTO,DOS_PUNTOS, CARACTER
}